In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from matplotlib import scale

In [44]:
df=pd.read_csv("Advertising.csv")
X=df.drop('sales',axis=1)
y=df['sales']

In [45]:
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [46]:
X

        TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [47]:
from sklearn.preprocessing import PolynomialFeatures

In [48]:
polynomial_converter=PolynomialFeatures(degree=3,include_bias=False)

In [49]:
poly_features=polynomial_converter.fit_transform(X)
poly_features

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
X_train,X_test,y_train,y_test=train_test_split(poly_features,y,test_size=0.3,random_state=101)

In [52]:
from sklearn.preprocessing import StandardScaler

In [53]:
scaler=StandardScaler()

In [54]:
scaler.fit(X_train)

StandardScaler()

In [55]:
X_train=scaler.transform(X_train)
X_train

array([[ 0.49300171, -0.33994238,  1.61586707, ..., -0.16360242,
         0.54694754,  1.37075536],
       [ 1.61337153,  1.32852213,  1.90079242, ...,  2.63236858,
         2.6297449 ,  1.95593378],
       [-0.84811893, -1.58789957, -1.02319564, ..., -0.72634944,
        -0.61593941, -0.54133745],
       ...,
       [ 1.04606563, -1.30982215,  0.27064572, ..., -0.71065643,
        -0.53420112, -0.20690952],
       [ 0.74817069,  0.03987068, -1.26608283, ..., -0.66805936,
        -0.61031703, -0.54616941],
       [ 0.13813882,  0.55533126,  1.01799092, ...,  0.61006767,
         0.67881488,  0.45425942]])

In [56]:
X_test=scaler.transform(X_test)
X_test

array([[-0.91339472,  1.76259419,  0.68168558, ...,  2.09516506,
         0.89465642,  0.09868885],
       [ 1.23121149,  0.23655959, -1.19601922, ..., -0.62566104,
        -0.60402516, -0.54547726],
       [-0.46002473, -0.40776614,  0.35005115, ..., -0.43068575,
        -0.23635113, -0.15776394],
       ...,
       [-1.33115973,  1.19965698, -1.18200649, ..., -0.47847952,
        -0.59569585, -0.54528297],
       [ 1.3522684 , -0.23142436, -1.4389064 , ..., -0.7233135 ,
        -0.61591305, -0.54660193],
       [ 0.27818504, -0.06186496,  0.01841672, ..., -0.32290124,
        -0.28905624, -0.33528306]])

Гребневая регрессия (Ridge Regression)

In [57]:
from sklearn.linear_model import Ridge
ridge_model=Ridge(alpha=10)

In [58]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [59]:
test_predictions=ridge_model.predict(X_test)
test_predictions

array([13.7469803 , 19.17764   , 11.8623393 , 16.25574551,  8.92891155,
        8.04595366, 20.13320851, 16.94847676, 10.29219174, 19.78365691,
       10.31758361, 13.44077317, 12.24228062, 23.23864236, 19.12656362,
        9.748809  , 12.84361521,  9.14248129,  8.82504966, 21.46989971,
        8.25222201, 18.8110776 , 28.39227333, 25.06911066,  9.11912241,
       11.8071711 , 20.85199462,  9.31962495, 12.25122303,  9.07811198,
        9.25275556, 19.87154568, 10.55955497,  7.86818084, 17.67220132,
        9.31442423, 10.1539168 ,  9.47802944,  8.63337302, 10.76209179,
       11.63848891, 10.38883411, 10.90270005,  8.40019284, 11.35336224,
       10.3514086 ,  8.00082147, 15.27139854, 12.94761469, 22.49762978,
       10.80165407, 13.01337743, 14.82204895, 11.37354043, 11.69628953,
        7.20576885, 25.53512232, 10.41926545, 17.38798022, 15.10158819])

In [60]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [61]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [62]:
MAE

0.5774404204714166

In [63]:
RMSE

np.float64(0.8946386461319648)

In [64]:
train_predictions=ridge_model.predict(X_train)
MAE=mean_absolute_error(y_train,train_predictions)
MAE

0.5288348183025304

Регрессия Лассо

In [65]:
from sklearn.linear_model import LassoCV

In [66]:
lasso_cv_model = LassoCV(eps=0.1,n_alphas=100,cv=5)

In [67]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [68]:
test_predictions = lasso_cv_model.predict(X_test)

In [69]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [70]:
MAE

0.6541723161252868

In [71]:
RMSE

np.float64(1.1308001022762548)

In [72]:
train_predictions = lasso_cv_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.691280714082071

Elastic Net

In [73]:
from sklearn.linear_model import ElasticNetCV

In [74]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7,.9, .95, .99, 1],tol=0.01)

In [75]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], tol=0.01)

In [76]:
test_predictions = elastic_model.predict(X_test)

In [77]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [78]:
MAE

0.566326211756945

In [79]:
RMSE

np.float64(0.7485546215633726)

In [80]:
train_predictions = elastic_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.4307582990472368

In [81]:
elastic_model.coef_

array([ 3.78993643,  0.89232919,  0.28765395, -1.01843566,  2.15516144,
       -0.3567547 , -0.271502  ,  0.09741081,  0.        , -1.05563151,
        0.2362506 ,  0.07980911,  1.26170778,  0.01464706,  0.00462336,
       -0.39986069,  0.        ,  0.        , -0.05343757])